# Generated by Django 4.2.2 on 2023-06-09 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_company', models.CharField(choices=[('NP', 'New Post'), ('UkrP', 'Ukr Post'), ('MT', 'Meest'), ('JN', 'Justin')], default='', max_length=10)),
                ('addressee_first_name', models.CharField(max_length=32)),
                ('addressee_last_name', models.CharField(max_length=32)),
                ('addressee_phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='eshop.cart'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(choices=[('PayPal', 'PayPal'), ('Liqpay', 'Liqpay'), ('Portmone', 'Portmone')], default='PayPal', max_length=30)),
                ('products_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_editor', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
