# Generated by Django 4.2.2 on 2023-06-14 10:29

from django.db import migrations, models
import django.db.models.query


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0003_remove_payment_editor_purchasehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasehistory',
            name='products',
            field=models.ManyToManyField(default=django.db.models.query.QuerySet.none, to='eshop.product'),
        ),
    ]
