# Generated by Django 4.2.2 on 2023-06-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0004_alter_purchasehistory_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasehistory',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='eshop.product'),
        ),
    ]
