# Generated by Django 4.2.2 on 2023-06-15 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0009_alter_payment_order_alter_payment_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='owner',
        ),
    ]
