# Generated by Django 4.2.2 on 2023-06-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0011_alter_payment_order_alter_shipment_order'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'Active')), fields=('user', 'status'), name='unique_active_order'),
        ),
    ]
