name: flake8

on:
  - pull_request

jobs:
  flake8: #job's name
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout #step name
        uses: actions/checkout@v2 #This action checks-out your repository under $GITHUB_WORKSPACE

      - name: Python setup # step name
        uses: actions/setup-python@v2 #Set up python version
        with:
          python-version: '3.8'

      - name: Install dependencies #step name
        run: pip install -r requirements.txt

      - name: Run flake8 #step name
        run: flake8

      - name: Print PYTHONPATH
        run: echo $PYTHONPATH

      - name: Set Environment Variables
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          # Add other environment variables as needed
        run: |
          echo "export DB_NAME=$DB_NAME" >> $GITHUB_ENV
          echo "export DB_USER=$DB_USER" >> $GITHUB_ENV
          echo "export DB_PASSWORD=$DB_PASSWORD" >> $GITHUB_ENV

      - name: Run tests #step name
        run: python manage.py test