name: flake8

on:
  - pull_request

jobs:
  flake8:
    runs-on: ubuntu-latest
    env:  # Set the environment variables here
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      # Add other environment variables as needed
    steps:
      - name: Repository checkout
        uses: actions/checkout@v2

      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run flake8
        run: flake8

      - name: Print PYTHONPATH
        run: echo $PYTHONPATH

      - name: Run tests
        run: python manage.py test